### ISSUE TITLE
GLTools.cpp fails to compile with gcc 4.4.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ljfc/oglsuperbible5#4]
```
What steps will reproduce the problem?
1. Compile GLTools.cpp with gcc 4.4.5

What is the expected output? What do you see instead?

I expect it to compile.  Instead, it gives the error:

GLTools.cpp: In function ‘GLuint gltLoadShaderTripletWithAttributes(const 
char*, const char*, const char*, ...)’:
GLTools.cpp:1255: warning: format not a string literal and no format arguments
GLTools.cpp:1262: error: jump to label ‘failed’
GLTools.cpp:1214: error:   from here
GLTools.cpp:1233: error:   crosses initialization of ‘int iArgCount’
GLTools.cpp:1262: error: jump to label ‘failed’
GLTools.cpp:1208: error:   from here
GLTools.cpp:1233: error:   crosses initialization of ‘int iArgCount’
GLTools.cpp:1262: error: jump to label ‘failed’
GLTools.cpp:1200: error:   from here
GLTools.cpp:1233: error:   crosses initialization of ‘int iArgCount’
GLTools.cpp:1262: error: jump to label ‘failed’
GLTools.cpp:1194: error:   from here
GLTools.cpp:1233: error:   crosses initialization of ‘int iArgCount’
GLTools.cpp:1262: error: jump to label ‘failed’
GLTools.cpp:1187: error:   from here
GLTools.cpp:1233: error:   crosses initialization of ‘int iArgCount’
GLTools.cpp:1262: error: jump to label ‘failed’
GLTools.cpp:1181: error:   from here
GLTools.cpp:1233: error:   crosses initialization of ‘int iArgCount’


What version of the product are you using? On what operating system?

SVN r176

Please provide any additional information below.

Attached is a patch that fixes it for me.

```

Original issue reported on code.google.com by `syd...@gmail.com` on 30 Oct 2010 at 10:11

Attachments:
- [GLTools.cpp.patch](https://storage.googleapis.com/google-code-attachments/oglsuperbible5/issue-4/comment-0/GLTools.cpp.patch)
